import { NextResponse } from 'next/server';
import { getCurrentUser } from '@/lib/supabase/server';
import { getSupabaseAdminClient } from '@/lib/supabase/admin';
import { orderUpdateSchema } from '@/lib/operations/validation';
export const runtime='nodejs';
async function authorized(){const user=await getCurrentUser();const db=getSupabaseAdminClient();if(!user?.email||!user.email_confirmed_at||!db)return {db:null,member:null};const {data}=await db.from('crew_members').select('id,full_name,email').eq('email',user.email.trim().toLowerCase()).eq('active',true).maybeSingle();return {db,member:data};}
export async function GET(){const {db,member}=await authorized();if(!db||!member)return NextResponse.json({ok:false,error:'Acceso exclusivo para trabajadores registrados.'},{status:401});
 const {data:orders,error}=await db.from('work_orders').select('id,lead_id,service_date,start_time,duration_minutes,status,price,paid_amount,payment_method,notes,leads(customer_name,customer_phone,address,city,has_gate_code,gate_code,additional_notes)').eq('crew_member_id',member.id).order('service_date',{ascending:true}).limit(250);
 if(error)return NextResponse.json({ok:false,error:'No se pudieron consultar las órdenes.'},{status:503});return NextResponse.json({ok:true,data:{member,orders:orders??[]}},{headers:{'Cache-Control':'no-store'}});
}
export async function PATCH(request:Request){const {db,member}=await authorized();if(!db||!member)return NextResponse.json({ok:false,error:'No autorizado.'},{status:401});const parsed=orderUpdateSchema.pick({id:true,status:true,paid_amount:true,payment_method:true,notes:true}).safeParse(await request.json().catch(()=>null));if(!parsed.success)return NextResponse.json({ok:false,error:'Revise el estado, método de pago y notas.'},{status:422});const {id,...changes}=parsed.data;const {data:current,error:lookup}=await db.from('work_orders').select('id,lead_id,status,price,paid_amount,payment_method').eq('id',id).eq('crew_member_id',member.id).maybeSingle();if(lookup||!current)return NextResponse.json({ok:false,error:'Orden no asignada.'},{status:404});if(current.status==='cancelled')return NextResponse.json({ok:false,error:'Una orden cancelada solo puede reabrirla el administrador.'},{status:422});if(changes.status==='cancelled')return NextResponse.json({ok:false,error:'Contacte al administrador para cancelar.'},{status:422});if((changes.status==='in_progress'||changes.status==='completed')&&current.status==='scheduled'){const {data:history,error:historyError}=await db.from('work_orders').select('id,price,paid_amount').eq('lead_id',current.lead_id).eq('status','completed');if(historyError)return NextResponse.json({ok:false,error:'No se pudo verificar el historial de pagos.'},{status:503});const overdue=(history??[]).filter(row=>row.id!==id&&Number(row.paid_amount)<Number(row.price)).length;if(overdue>=2)return NextResponse.json({ok:false,error:'Este cliente tiene dos cortes sin liquidar. Consulte al dueño antes de iniciar otro servicio.'},{status:409});}if(changes.paid_amount!==undefined&&changes.paid_amount>Number(current.price))return NextResponse.json({ok:false,error:'El pago supera el precio del servicio.'},{status:422});if((changes.paid_amount??Number(current.paid_amount))>0&&!(changes.payment_method??current.payment_method))return NextResponse.json({ok:false,error:'Indique el método de pago.'},{status:422});const update:Record<string,unknown>={...changes};if(changes.status==='completed'&&current.status!=='completed')update.completed_at=new Date().toISOString();if(changes.status&&changes.status!=='completed'&&current.status==='completed')update.completed_at=null;if(changes.paid_amount!==undefined)update.paid_at=changes.paid_amount===Number(current.price)?new Date().toISOString():null;
 const {data,error}=await db.from('work_orders').update(update).eq('id',id).eq('crew_member_id',member.id).select('id,status,paid_amount,payment_method,notes,completed_at').single();return error?NextResponse.json({ok:false,error:'No se pudo actualizar.'},{status:503}):NextResponse.json({ok:true,data});}
