'use client';
import * as React from 'react';
import Link from 'next/link';
import { getSupabaseBrowserClient } from '@/lib/supabase/client';
import type { OpsPaymentMethod, OrderStatus } from '@/lib/operations/types';
type CrewOrder={id:string;service_date:string;start_time:string;duration_minutes:number;status:OrderStatus;price:number|string;paid_amount:number|string;payment_method:OpsPaymentMethod|null;notes:string|null;leads:{customer_name:string;customer_phone:string;address:string;city:string|null;has_gate_code:boolean;gate_code:string|null;additional_notes:string|null}|null};
type Payload={member:{full_name:string};orders:CrewOrder[]};
export default function CrewPage(){const [user,setUser]=React.useState<string|null>(null),[data,setData]=React.useState<Payload|null>(null),[message,setMessage]=React.useState(''),[ready,setReady]=React.useState(false);
 const load=React.useCallback(async()=>{try{const r=await fetch('/api/crew/orders',{cache:'no-store'}),j=await r.json();if(!r.ok)throw Error(j.error??'No se pudieron cargar las casas.');setData(j.data);setMessage('');}catch(e){setData(null);setMessage(e instanceof Error?e.message:'Error de conexión');}},[]);
 React.useEffect(()=>{const auth=getSupabaseBrowserClient();void auth?.auth.getUser().then(({data})=>{setUser(data.user?.email??null);setReady(true);if(data.user)void load();});const timer=setInterval(()=>{if(auth)void load();},60000);return()=>clearInterval(timer);},[load]);
 const login=async()=>{const auth=getSupabaseBrowserClient();const {error}=await auth!.auth.signInWithOAuth({provider:'google',options:{redirectTo:`${window.location.origin}/crew`}});if(error)setMessage(error.message);};
 const save=async(order:Partial<CrewOrder>&{id:string})=>{try{const r=await fetch('/api/crew/orders',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(order)}),j=await r.json();if(!r.ok)throw Error(j.error??'No se pudo guardar');await load();setMessage('Visita guardada en el panel del dueño.');}catch(e){setMessage(e instanceof Error?e.message:'Error al guardar');}};
 return <main className="min-h-screen bg-emerald-50 text-slate-900"><header className="border-b border-emerald-200 bg-white"><div className="mx-auto flex max-w-5xl items-center justify-between gap-2 px-4 py-4"><Link className="font-black text-emerald-900" href="/">NIETO GREEN CARE</Link><span className="text-sm font-semibold">Casas asignadas</span>{user&&<button className="text-sm text-emerald-800 underline" onClick={async()=>{await getSupabaseBrowserClient()?.auth.signOut();setUser(null);setData(null);}}>Salir</button>}</div></header><div className="mx-auto max-w-5xl space-y-5 px-4 py-8">{!ready&&<p>Comprobando acceso…</p>}{ready&&!user&&<section className="rounded-2xl border border-emerald-200 bg-white p-8"><h1 className="text-2xl font-bold">Acceso del equipo</h1><p className="mt-2 text-slate-700">Ingresa con el correo de Google que registró el dueño. Solo podrás ver tus visitas asignadas.</p><button className="mt-5 rounded-lg bg-emerald-600 px-5 py-3 font-bold text-white" onClick={()=>void login()}>Continuar con Google</button></section>}{message&&<p role="status" className="rounded-lg border border-emerald-300 bg-white p-3 text-sm">{message}</p>}{user&&data&&<><div><h1 className="text-2xl font-bold">Hola, {data.member.full_name}</h1><p className="text-sm text-slate-600">{data.orders.length} visitas asignadas · horarios de Texas</p></div>{data.orders.map(order=><CrewCard key={order.id} order={order} save={save}/>)}{!data.orders.length&&<p className="rounded-lg bg-white p-6">Todavía no tienes casas asignadas.</p>}</>}</div></main>;
}
function CrewCard({order,save}:{order:CrewOrder;save:(updates:Partial<CrewOrder>&{id:string})=>Promise<void>}){const [status,setStatus]=React.useState(order.status),[paid,setPaid]=React.useState(String(order.paid_amount)),[method,setMethod]=React.useState<OpsPaymentMethod|''>(order.payment_method??''),[notes,setNotes]=React.useState(order.notes??''),[busy,setBusy]=React.useState(false);React.useEffect(()=>{setStatus(order.status);setPaid(String(order.paid_amount));setMethod(order.payment_method??'');setNotes(order.notes??'');},[order]);const lead=order.leads;
 return <section className="rounded-2xl border border-emerald-200 bg-white p-5 shadow-sm"><div className="flex flex-wrap justify-between gap-3"><div><h2 className="text-lg font-bold">{lead?.address??'Casa asignada'}</h2><p className="text-sm text-slate-700">{lead?.customer_name} · {lead?.city} · <a className="text-emerald-700 underline" href={`tel:${lead?.customer_phone}`}>{lead?.customer_phone}</a></p><p className="text-sm">{order.service_date} · {order.start_time.slice(0,5)} · {order.duration_minutes} minutos</p></div><p className="font-bold text-emerald-800">${Number(order.price).toFixed(2)} · {Number(order.paid_amount)>=Number(order.price)?'Pagado':'Pago pendiente'}</p></div>{lead?.has_gate_code&&<p className="mt-3 rounded-lg bg-amber-50 p-3 text-sm">Acceso al portón: {lead.gate_code||'Consultar al dueño'}</p>}{lead?.additional_notes&&<p className="mt-2 text-sm">Nota del cliente: {lead.additional_notes}</p>}<div className="mt-4 grid gap-3 sm:grid-cols-3"><label className="text-sm font-semibold">Estado<select className="block w-full rounded-lg border p-2" value={status} onChange={e=>setStatus(e.target.value as OrderStatus)} disabled={order.status==='cancelled'}><option value="scheduled">Agendada</option><option value="in_progress">En proceso</option><option value="completed">Finalizada</option>{order.status==='cancelled'&&<option value="cancelled">Cancelada</option>}</select></label><label className="text-sm font-semibold">Pago recibido ($)<input className="block w-full rounded-lg border p-2" type="number" min="0" max={Number(order.price)} step="0.01" value={paid} onChange={e=>setPaid(e.target.value)}/></label><label className="text-sm font-semibold">Método de pago<select className="block w-full rounded-lg border p-2" value={method} onChange={e=>setMethod(e.target.value as OpsPaymentMethod|'')}><option value="">Sin registrar</option>{(['cash','cash_app','venmo','zelle','check','other'] as const).map(key=><option key={key} value={key}>{key==='cash_app'?'Cash App':key==='check'?'Cheque':key}</option>)}</select></label></div><label className="mt-3 block text-sm font-semibold">Notas de la visita<textarea className="mt-1 block w-full rounded-lg border p-2" value={notes} maxLength={2000} onChange={e=>setNotes(e.target.value)}/></label><button className="mt-4 rounded-lg bg-emerald-600 px-4 py-2 font-bold text-white disabled:opacity-50" disabled={busy||order.status==='cancelled'} onClick={async()=>{setBusy(true);await save({id:order.id,status,paid_amount:Number(paid),payment_method:method||null,notes:notes||null});setBusy(false);}}>Guardar visita</button></section>;
}
