'use client';
import * as React from 'react';
import type { OpsData, OpsPaymentMethod } from '@/lib/operations/types';
import { invoiceGroupKey } from '@/lib/operations/invoice-group';

const field='rounded-lg border border-slate-300 bg-white px-3 py-2 text-slate-900';
const button='rounded-lg bg-emerald-700 px-4 py-2 font-bold text-white disabled:opacity-40';
const phone=(value:string)=>value.replace(/\D/g,'').slice(-10);
export function CustomerHistory({data,reload}:{data:OpsData;reload:()=>Promise<void>}){
 const [search,setSearch]=React.useState(''),[customer,setCustomer]=React.useState(''),[editing,setEditing]=React.useState<string|null>(null);
 const [selected,setSelected]=React.useState<Record<string,string>>({});
 const [method,setMethod]=React.useState<OpsPaymentMethod>('cash');
 const [notice,setNotice]=React.useState(''),[busy,setBusy]=React.useState(false);
 const customers=Array.from(new Map(data.leads.map(lead=>[phone(lead.customer_phone)||lead.id,lead])).entries());
 const leads=data.leads.filter(lead=>(phone(lead.customer_phone)||lead.id)===customer);
 const ids=new Set(leads.map(lead=>lead.id));
 const orders=data.orders.filter(order=>ids.has(order.lead_id)).sort((a,b)=>b.service_date.localeCompare(a.service_date));
 const groups=Array.from(new Map(data.invoices.filter(invoice=>orders.some(order=>order.id===invoice.order_id)).map(invoice=>[invoiceGroupKey(invoice.invoice_number),invoice])).entries());
 const request=async(url:string,body:unknown)=>{setBusy(true);setNotice('');try{const response=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const result=await response.json();if(!response.ok||!result.ok)throw Error(result.error||'No se pudo guardar.');setSelected({});setEditing(null);await reload();setNotice('Cambios guardados.');}catch(error){setNotice(error instanceof Error?error.message:'Error');}finally{setBusy(false);}};
 return <section className="rounded-lg border border-emerald-200 bg-white p-5 text-slate-900"><h3 className="text-xl font-bold">Historial y cobro por cliente</h3>
  <input aria-label="Buscar cliente por nombre" placeholder="Buscar cliente por nombre" className={`${field} my-3 w-full`} value={search} onChange={event=>setSearch(event.target.value)}/>
  <div className="flex max-h-40 flex-wrap gap-2 overflow-auto">{customers.filter(([,lead])=>lead.customer_name.toLocaleLowerCase().includes(search.toLocaleLowerCase())).map(([key,lead])=><button key={key} className={customer===key?button:`${field} text-left`} onClick={()=>{setCustomer(key);setSelected({});setEditing(null);}}>{lead.customer_name} · {lead.customer_phone}</button>)}</div>
  {customer&&<><div className="my-4 text-sm">{leads.map(lead=><div key={lead.id}><p className="font-bold">{lead.customer_name} · {lead.address}</p><p>{lead.customer_phone} · {lead.customer_email}</p><p>{lead.details}</p></div>)}</div>
   <div className="max-h-96 space-y-2 overflow-auto">{orders.map(order=>{const invoiced=data.invoices.some(invoice=>invoice.order_id===order.id);const eligible=order.status==='completed'&&Number(order.paid_amount)<Number(order.price)&&!invoiced;return <div key={order.id} className="flex flex-wrap items-center gap-3 border-t py-3"><label className="flex items-center gap-2"><input type="checkbox" disabled={!eligible||busy} checked={order.id in selected} onChange={event=>setSelected(current=>{const next={...current};if(event.target.checked)next[order.id]=String(order.price);else delete next[order.id];return next;})}/>{order.service_date}</label><span>{order.status==='completed'?'Realizado':order.status==='cancelled'?'Cancelado':'Agendado'} · ${Number(order.price).toFixed(2)} · Pagado: ${Number(order.paid_amount).toFixed(2)} · {order.payment_method??'Sin método de pago'}</span>{order.id in selected&&<label>Precio factura $ <input aria-label={`Precio de la visita ${order.service_date}`} type="number" step="0.01" min={Number(order.paid_amount)} className={`${field} w-28`} value={selected[order.id]} onChange={event=>setSelected({...selected,[order.id]:event.target.value})}/></label>}{invoiced&&<span className="text-sm">Con factura</span>}</div>;})}</div>
   <p className="my-3 font-bold">Total seleccionado: ${Object.values(selected).reduce((sum,value)=>sum+Number(value||0),0).toFixed(2)}</p>
   <button className={button} disabled={busy||!Object.keys(selected).length||Object.values(selected).some(value=>!value.trim()||!Number.isFinite(Number(value)))} onClick={()=>void request(editing?'/api/admin/operations/invoices':'/api/admin/operations/invoice-group',{...(editing?{action:'edit',invoice_id:editing}:{}),items:Object.entries(selected).map(([orderId,value])=>({orderId,price:Number(value)}))})}>{editing?'Guardar precios de la factura':'Generar factura de las fechas seleccionadas'}</button>
   <label className="my-4 block">Método de pago <select className={field} value={method} onChange={event=>setMethod(event.target.value as OpsPaymentMethod)}><option value="cash">Efectivo</option><option value="cash_app">Cash App</option><option value="venmo">Venmo</option><option value="zelle">Zelle</option></select></label>
   {groups.map(([key,invoice])=>{const rows=data.invoices.filter(row=>invoiceGroupKey(row.invoice_number)===key);const paid=rows.every(row=>Number(orders.find(order=>order.id===row.order_id)?.paid_amount??0)>=Number(row.total));return <div key={key} className="mt-3 rounded-lg border p-3"><p className="font-semibold">{rows.map(row=>orders.find(order=>order.id===row.order_id)?.service_date).join(' · ')} · ${rows.reduce((sum,row)=>sum+Number(row.total),0).toFixed(2)} · {paid?'Pagada':'Pendiente de pago'}</p><div className="mt-2 flex flex-wrap gap-2"><button className={button} disabled={busy||rows.some(row=>Boolean(row.sent_at))||paid} onClick={()=>{setEditing(invoice.id);setSelected(Object.fromEntries(rows.map(row=>[row.order_id,String(row.total)])));}}>Modificar precios</button><a className={button} target="_blank" rel="noreferrer" href={`/api/admin/operations/invoice-file?id=${invoice.id}`}>Descargar factura</a><button disabled={busy||rows.some(row=>Boolean(row.sent_at))} className={button} onClick={()=>void request('/api/admin/operations/invoices',{action:'send',invoice_id:invoice.id})}>Enviar al cliente</button><button disabled={busy||paid} className={button} onClick={()=>void request('/api/admin/operations/invoices',{action:'pay',invoice_id:invoice.id,payment_method:method})}>Registrar pago conjunto</button></div></div>;})}
  </>}{notice&&<p role="status" className="mt-3">{notice}</p>}
 </section>;
}
