'use client';
import * as React from 'react';
import type { PricingRule } from '@/lib/types';

type Props = { rules: PricingRule[]; onCreated: (rule: PricingRule) => void; onUpdated: (rule: PricingRule) => void };
export function LawnRateEditor({rules,onCreated,onUpdated}: Props) {
 const [frequency,setFrequency]=React.useState<'weekly'|'bi_weekly'>('weekly');
 const [min,setMin]=React.useState(''); const [max,setMax]=React.useState(''); const [price,setPrice]=React.useState('');
 const [notice,setNotice]=React.useState(''); const [working,setWorking]=React.useState(false);
 const bands=rules.filter((r)=>r.service_key?.startsWith('lawn_'));
 async function save(url:string,method:'POST'|'PATCH',body:unknown,callback:(r:PricingRule)=>void) {setWorking(true);setNotice('');try {const response=await fetch(url,{method,headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const result=await response.json();if(!response.ok||!result.ok) throw new Error(result.error||'No se pudo guardar');callback(result.data);setNotice('Tarifa guardada. Ya está disponible en el cotizador.');}catch(e){setNotice(e instanceof Error?e.message:'Error al guardar');}finally{setWorking(false);}}
 const add=()=>{const low=Number(min), high=max.trim()?Number(max):null, amount=Number(price);if(min.trim()===''||price.trim()===''||low<0||!Number.isFinite(low)||high!==null&&(!Number.isFinite(high)||high<=low)||!Number.isFinite(amount)||amount<=0){setNotice('Indique un rango válido y un precio mayor que cero.');return;}if(bands.some((r)=>r.service_key===`lawn_${frequency}`&&low<Number(r.max_sq_ft??Infinity)&&(high??Infinity)>Number(r.min_sq_ft))){setNotice('El rango se superpone con otra tarifa activa.');return;}void save('/api/admin/pricing','POST',{name:`Césped ${min}–${max||'+'} ft² ${frequency}`,service_key:`lawn_${frequency}`,min_sq_ft:low,max_sq_ft:high,price:amount,is_active:true},onCreated);};
 return <section className="rounded-2xl border border-emerald-500 bg-emerald-950 p-5 text-white"><h2 className="text-xl font-bold">Precios instantáneos por tamaño del césped</h2><p className="mt-2 text-sm text-emerald-100">Mida primero sus casas de referencia y registre rangos por frecuencia. No hay precios de ejemplo publicados. Rango mínimo inclusivo y máximo exclusivo. El cotizador solo acepta solicitudes cuando existe una tarifa para la medida.</p><div className="mt-4 grid gap-3 sm:grid-cols-5"><label>Frecuencia<select className="mt-1 w-full rounded-lg bg-white p-2 text-slate-900" value={frequency} onChange={e=>setFrequency(e.target.value as typeof frequency)}><option value="weekly">Semanal</option><option value="bi_weekly">Quincenal</option></select></label><label>Desde (ft²)<input className="mt-1 w-full rounded-lg bg-white p-2 text-slate-900" type="number" min="0" value={min} onChange={e=>setMin(e.target.value)} /></label><label>Hasta (ft²)<input className="mt-1 w-full rounded-lg bg-white p-2 text-slate-900" type="number" min="0" placeholder="Sin límite" value={max} onChange={e=>setMax(e.target.value)} /></label><label>USD / corte<input className="mt-1 w-full rounded-lg bg-white p-2 text-slate-900" type="number" min="0.01" step="0.01" value={price} onChange={e=>setPrice(e.target.value)} /></label><button className="self-end rounded-lg bg-lime-500 px-3 py-2 font-bold text-slate-950 disabled:opacity-50" disabled={working} onClick={add}>Agregar rango</button></div>{notice&&<p role="status" className="mt-3 text-sm text-lime-200">{notice}</p>}<div className="mt-5 space-y-2">{bands.map((r)=><Band key={r.id} rule={r} save={(changes)=>void save('/api/admin/pricing','PATCH',{id:r.id,changes},onUpdated)} />)}{!bands.length&&<p className="text-sm text-lime-200">Sin rangos configurados. Agregue los precios reales antes de ofrecer cotizaciones instantáneas.</p>}</div></section>;
}
function Band({rule,save}:{rule:PricingRule;save:(change:Record<string,unknown>)=>void}) {const [price,setPrice]=React.useState(String(rule.price));return <div className="flex flex-wrap items-center justify-between gap-3 rounded-lg border border-white/20 p-3 text-sm"><span>{rule.service_key==='lawn_weekly'?'Semanal':'Quincenal'} · {rule.min_sq_ft}–{rule.max_sq_ft??'+'} ft² {rule.is_active?'':'· pausada'}</span><div className="flex gap-2"><input aria-label="Precio por corte" className="w-24 rounded bg-white p-2 text-slate-900" type="number" min="0.01" step="0.01" value={price} onChange={e=>setPrice(e.target.value)}/><button className="rounded bg-lime-500 px-3 text-slate-950" onClick={()=>Number(price)>0&&save({price:Number(price)})}>Guardar</button><button className="rounded border border-white/50 px-3" onClick={()=>save({is_active:!rule.is_active})}>{rule.is_active?'Pausar':'Activar'}</button></div></div>}
